package clientes.vista;

import administracion.controlador.Hash;
import administracion.controlador.ProcesosRepetidos;
import administracion.controlador.UsuarioAplicacion;
import administracion.modelo.UsuarioAplicacionDAO;
import clientes.controlador.Pedidos;
import clientes.modelo.PedidosDAO;
import java.util.List;

public class Prcs_RastrearP extends javax.swing.JInternalFrame {

    ProcesosRepetidos procesosr = new ProcesosRepetidos();
    Pedidos pedidos = new Pedidos();
    PedidosDAO pedidosDAO = new PedidosDAO();

    public Prcs_RastrearP() {
        initComponents();
        diseño();
        String id=LOGIN_Clientes.idCliente;
        Txt_idC.setText(id);
        cargarDatos("");
    }

    public void diseño() {
        setTitle("Rastrear Pedido");
        procesosr.cursorMano(Tbl_Datos);
    }

    private void cargarDatos(String query) {
        ProcesosRepetidos procesosr = new ProcesosRepetidos();
        PedidosDAO.codigoCliente = query;
        PedidosDAO.codigoPedido = query;
        String encabezado[] = {"ID", "REMITENTE", "DESTINATARIO", "NOMBRE DESTINATARIO", "ESTADO"};
        int cantidadcolumnas = encabezado.length;
        procesosr.llenarColumnas(encabezado, cantidadcolumnas, Tbl_Datos);
        String datos[] = new String[cantidadcolumnas];
        int tamaño[] = {25, 150, 150, 100, 150};
        PedidosDAO pedidosDAO = new PedidosDAO();
        List<Pedidos> listadoClientes = pedidosDAO.select();
        for (Pedidos listado : listadoClientes) {
            if (listado.getIdCliente().equals(Txt_idC.getText())) {
            datos[0] = listado.getIdPedido();
            datos[1] = listado.getDireR();
            datos[2] = listado.getDireD();
            datos[3] = listado.getNomD();
            if (listado.getEstado().equals("0")) {
                datos[4] = "Pendiente de Recolectar";
            } if (listado.getEstado().equals("1")){
                datos[4] = "Recoleccion Programada";
            }
            procesosr.llenarFilas(datos, tamaño, Tbl_Datos);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_estados = new javax.swing.ButtonGroup();
        Pnl_datos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();
        Lbl_id4 = new javax.swing.JLabel();
        Txt_busqueda = new javax.swing.JTextField();
        Lbl_idC = new javax.swing.JLabel();
        Txt_idC = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 239, 180));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Pnl_datos.setBackground(new java.awt.Color(252, 239, 180));
        Pnl_datos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 78, 65), 1, true));

        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tbl_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_DatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbl_Datos);

        Lbl_id4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_id4.setText("BUSCAR ID PEDIDO:");

        Txt_busqueda.setBackground(new java.awt.Color(252, 239, 180));
        Txt_busqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_busqueda.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(88, 129, 87)));
        Txt_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_busquedaKeyReleased(evt);
            }
        });

        Lbl_idC.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_idC.setText("ID:");

        Txt_idC.setEditable(false);
        Txt_idC.setBackground(new java.awt.Color(252, 239, 180));
        Txt_idC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_idC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(88, 129, 87)));
        Txt_idC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_idCKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Pnl_datosLayout = new javax.swing.GroupLayout(Pnl_datos);
        Pnl_datos.setLayout(Pnl_datosLayout);
        Pnl_datosLayout.setHorizontalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addComponent(Lbl_idC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_idC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(Lbl_id4)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_datosLayout.setVerticalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_id4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_idC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_idC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_DatosMouseClicked
        
    }//GEN-LAST:event_Tbl_DatosMouseClicked

    private void Txt_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_busquedaKeyReleased
        String query = Txt_busqueda.getText();
        cargarDatos(query);
    }//GEN-LAST:event_Txt_busquedaKeyReleased

    private void Txt_idCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_idCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_idCKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Bg_estados;
    private javax.swing.JLabel Lbl_id4;
    private javax.swing.JLabel Lbl_idC;
    private javax.swing.JPanel Pnl_datos;
    private javax.swing.JTable Tbl_Datos;
    private javax.swing.JTextField Txt_busqueda;
    private javax.swing.JTextField Txt_idC;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
